---
- name: Create LinuxDevOps VMs
  hosts: localhost
  connection: local
  tags:
    - VM
    - LinuxDevOpsVM
  tasks: 
     - name: Apply DevOpsVm Role
       include_role:
          name: LinuxDevOpsVM
       with_items: "{{ groups['linux_devops'] }}" 

- name: Create Storage VMs
  hosts: localhost
  connection: local
  tags:
    - VM
    - Storage
  tasks: 
     - name: Apply DevOpsVm Role
       include_role:
          name: LinuxDevOpsVM
       with_items: "{{ groups['linux_storage'] }}" 


- name: Install Base Package on linux VMs
  hosts: linux_hosts
  become: yes
  tags:
    - BaseLinuxPackages
  tasks:
    - name: Install Linux packages
      include_role:
          name: BaseLinuxPackages  

- name: Apply roles to linuxdevops
  hosts: linux_devops
  become: yes
  roles:
     - role:  LinuxDomainJoined
       tags: ['DomainJoin']

     - role: Docker
       tags: ['Docker']

     - role: Jenkins-docker
       tags: ['Jenkins']
     
     - role: Nexus-docker
       tags: ['Nexus']  

     - role: Traefik-docker
       tags: ['Traefik']

- name: Apply roles to Storage VM
  hosts: linux_storage
  become: yes
  roles:
     - role: LinuxDomainJoined
       tags: ['DomainJoined']

     


