---
- name: Create LinuxDevOps VMs
  hosts: localhost
  connection: local
  tags:
    - VM
    - LinuxDevOpsVM
  tasks: 
     - name: Apply DevOpsVm Role
       include_role:
          name: LinuxDevOpsVM
       with_items: "{{ groups['linux_devops'] }}" 

- name: Install Base Package on linux VMs
  hosts: linux_hosts
  become: yes
  tags:
    - BaseLinuxPackages
  tasks:
    - name: Install Linux packages
      include_role:
          name: BaseLinuxPackages  

- name: Apply roles to linuxdevops
  hosts: linux_devops
  become: yes
  roles:
     - role:  LinuxDomainJoined
       tags: ['DomainJoin']

     - role: Docker
       tags: ['Docker']

     - role: Jenkins
       tags: ['Jenkins']
     







