all:
  vars:
     ansible_user: ansible
     ansible_password: DevOpsCloud123%
     domain_name: aesondev
     domain_ext: cloud 
     domain: "{{ domain_name }}.{{ domain_ext }}"
     vcenter_hostname: vcenter.aesondev.cloud
     vcenter_username: ansible@vsphere.local
     vcenter_password: DevOpsCloud123%
     vm_datacenter: FLUXYSDEMO 
     private_ip_netmask: 255.0.0.0
     private_ip_dns: 10.0.0.1
     private_network_name: Internal
     public_ip_netmask: 255.255.255.255
     public_ip_dns: 213.186.33.99
     public_network_name: VM Network
     public_ip_gateway: 54.37.85.254 
     ad_user: ansible-domain
     ad_password: DevOpsCloud123%      
linux_hosts:
         vars:
           ansible_sudo_pass: DevOpsCloud123%
           ad_ou: "OU=LinuxServers,DC={{ domain_name }},DC={{ domain_ext }}"     
         children:
           jenkins_servers:

windows_hosts:
         vars: 
           ansible_connection: winrm
           ansible_winrm_transport: basic
           ansible_winrm_server_cert_validation: ignore


jenkins_servers:
        vars: 
           vm_template_name: LinuxTemplateVM
           cpus: 2
           ram_mb: 4000
           disk_size_gb: 17
        hosts: 
           10.0.0.5:
                 vm_name: LINUXDEVOPS01 
                 private_ip: 10.0.0.5
                 public_ip: 51.255.31.149
                 public_nic_mac: 00:50:56:06:21:59
                 










