---
- name: Create the Docker Volume
  docker_volume:
    name: nexus-data


- name: Create Nexus container
  docker_container:
    name: nexus
    image: sonatype/nexus3
    state: started
    ports:
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data
