---
- name: Create the Docker Volume
  docker_volume:
    name: nexus-data


- name: Create Nexus container
  docker_container:
    name: nexus
    image: sonatype/nexus3
    state: started
    volumes:
      - nexus-data:/nexus-data
    labels:
      'traefik.backend' :  'nexus'
      'traefik.frontend' :  "Host:nexus.{{ domain_name }}.int"
      'traefik.docker.network' :  'bridge'
      'traefik.port' :  '8081'
      'traefik.enable' : 'true' 
